print("                            CURRICULUM VITAE                       ")
print("Nume,prenume:Dovgan Ana-Maria")
print("Data și locul nașterii:31.07.2004; or.Bălți")
print("E-mail:anisoaradovgan2004@gmail.com")
print("Telefon:+37368267482")
print("Adresa:Ivano Franco 17/1/97")
print("Naționalitate:moldoveancă")
print("Studii:L.T.,,Vasilie Alecsandri,, ;I.P.L.T.,,Mihai Eminescu,,")
print("Limbi străine:limba engleză,limba germană,limba rusă")
print("Calități:comunicabilă,prietenoasă,responsabilă")
